version: '3'
services:
  db:
    image: postgres:15
    container_name: prisma-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: infoteam_subject
    ports:
      - '5432:5432'
    networks:
      - app-network

  app:
    build: .
    container_name: infoteam-subject
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_OAUTH_ID=${GOOGLE_OAUTH_ID}
      - GOOGLE_OAUTH_SECRET=${GOOGLE_OAUTH_SECRET}
      - GOOGLE_OAUTH_CALLBACK=${GOOGLE_OAUTH_CALLBACK}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
